//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        public Clientes()
        {
            this.Pagos = new HashSet<Pagos>();
        }
    
        public int IdCliente { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Telefono { get; set; }
        public Nullable<System.DateTime> Ultimo_pago { get; set; }
        public Nullable<System.DateTime> Fecha_Creacion { get; set; }
    
        public virtual ICollection<Pagos> Pagos { get; set; }
    }
}
