//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagos
    {
        public int IdPago { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<double> Monto { get; set; }
        public Nullable<System.DateTime> Fecha_Pago { get; set; }
    
        public virtual Clientes Clientes { get; set; }
    }
}
